### ISSUE TITLE
wish: basic documentation

### ISSUE THREAD

**Issue by markstos** [keithy/groan#1]

**Comment by keithy** [comment]
Your wish is my sub-command.

**Comment by keithy** [comment]
groan is a work in progress:

roadmap:

1. Easier to roll your own command
2. Composable commands
3. auto-completion

**Comment by markstos** [comment]
I like `sub`, and am sorry to see it seems to be inactive (although, relatively feature-complete and mature).  I'm glad to see there's still some interest in this space.  I'll keep an eye on `groan`.

**Comment by keithy** [comment]
We are open for business and have some documentation!
